config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'
  resources :users
  post 'users/create'
  post 'users/new'
  get 'users/show'
  get 'armstrong/input'
  get 'armstrong', to: redirect('armstrong/input')
  get 'armstrong/result', as: :result_armstrong

  root 'armstrong#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :nickname
  validates_length_of :nickname, minimum: 3
  validates_length_of :password, minimum: 3


  def has_password?(submitted_password)
    password == submitted_password
  end
  def self.authenticate(nickname, submitted_password)
    user = find_by_nickname(nickname)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :authenticate, :except => [:signup, :signin, :new, :create]

  def current_user
    @_current_user ||= session[:current_user_id] &&
        User.find_by_id(session[:current_user_id])
  end

  private
  def authenticate
    unless current_user
      redirect_to sessions_new_path
    end
  end
end

app/controllers/armstrong_controller.rb
class ArmstrongController < ApplicationController
  def index
  end

  def input
  end

  def result
    @n = params[:number].to_i
    if @n < 1
      flash[:alert] = "There are't numbers with #{@n} digits"
      redirect_to armstrong_path
      return
    end

    if @n > 39
      @result = []
      return
    end

    if @n > 7
      flash[:alert] = "Very big number of digits. My computer will brake =("
      redirect_to armstrong_path
      return
    end

    @result = (10**(@n - 1)).upto(10**@n - 1).select do |num|
      num.digits.reduce(0) {|sum, dig| sum + dig ** @n}.equal? num
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def new
  end

  def create
    flash[:alert] = nil

    user = User.authenticate(params[:session][:nickname],
                             params[:session][:password])
    if user.nil?
      flash[:danger] = "Invalid nickname/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to armstrong_input_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    if user_params[:nickname].length < 3
      flash[:danger] = 'Nickname must be has got at least 3 symbols'
      redirect_to users_new_path
      return
    end
    if user_params[:password].length < 3
      flash[:danger] = 'Password must be has got at least 3 symbols'
      redirect_to users_new_path
      return
    end
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User was successfully created'
      redirect_to sessions_new_path
    else
      flash[:danger] = 'User already exist'
      redirect_to users_new_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      flash[:success] = 'User was successfully updated'
      redirect_to @user
    else
      flash[:danger] = 'Error'
      redirect_to edit_user_url
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    flash[:success] = 'User was successfully destroyed.'
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = @_current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nickname, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/armstrong_helper.rb
module ArmstrongHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    #cookies.permanent.signed[:remember_token] = [user.id]
    session[:current_user_id] = user.id
    self.current_user = user
  end

  def sign_out
    #cookies.delete(:remember_token)
    session[:current_user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/armstrong/index.html.erb
<div class="container" align="center">
  <div class="row">
    <div class="col-md-8 offset-md-2 center">
      <h1>Armstrong number</h1>
      <div class="jumbotron">
        In recreational number theory, a narcissistic number (also known as a pluperfect digital invariant (PPDI), an Armstrong number (after Michael F. Armstrong) or a plus perfect number) is a number that is the sum of its own digits each raised to the power of the number of digits. This definition depends on the base b of the number system used, e.g., b = 10 for the decimal system or b = 2 for the binary system.
      </div>
      <%= content_tag 'a', "Let's calculate some of them", role: 'button', class: 'btn btn-primary', href: armstrong_path %>
    </div>
  </div>
</div>

app/views/armstrong/input.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4" align="center">
      <h1>Armstrong numbers</h1>
      <%= bootstrap_form_tag url: result_armstrong_path, method: 'get' do |f| %>
        <% if flash[:alert] %>
          <%= f.number_field :number, label: 'Number of digits in number', class: 'is-invalid'%>
          <%= f.label flash[:alert], class: 'text-danger' %>
        <% else %>
          <%= f.number_field :number, label: 'Number of digits in number'%>
        <% end %>
        <%= f.primary 'Show numbers'%>
      <% end %>
    </div>
  </div>
</div>

app/views/armstrong/result.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3" align="center">
      <h1><%= "Armstrong numbers with #{@n} digits" %></h1>
      <% if @result.empty? %>
        <div class="alert alert-danger" role="alert"><%= "There are't armstrong numbers with #{@n} digits" %></div>
      <% else %>
        <table class="table table-bordered table-hover bg-white">
          <thead class="thead-dark">
          <tr>
            <th>№</th>
            <th >Armstrong number</th>
          </tr>
          </thead>
          <tbody>
          <% @result.each_with_index do |num, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= num %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
      <%= content_tag 'a', 'Go back', role: 'button', class: 'btn btn-primary', href: armstrong_path %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <span class="text-muted">Suldin Aleksandr, 2018</span>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <!-- Brand/logo -->
    <%= content_tag :a, 'Armstrong', class: 'navbar-brand', href: root_path %>

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= content_tag :a, 'Calculate', class: 'nav-link', href: armstrong_path %>
      </li>
      <li class="nav-item">
        <%= content_tag :a, 'Users', class: 'nav-link', href: users_path %>
      </li>
    </ul>
    <!--form class="form-inline"-->

      <% unless @_current_user %>
        <a role="button" class="btn btn-light" href="<%= sessions_new_path %>">Log In</a>
      <% else %>
        <span class="nickname-hello">Your are</span>
        <span class="nickname"><%= @_current_user.nickname %></span>
        <div class="btn-group" role="group" aria-label="Basic example">
          <a role="button" class="btn btn-light" href="<%= users_show_path %>">My account</a>
          <a role="button" class="btn btn-light" href="<%= sessions_destroy_path %>">Log Out</a>
        </div>
    <% end %>
    <!--/form-->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lr12</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'layouts/header' %>
    <main class="container" role="main">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3" align="center">
      <h1>Editing User</h1>
      <%= bootstrap_form_for :user, url: '/users/update',  method: 'put', local: true do |f| %>
        <% if flash[:danger] %>
          <%= f.text_field :nickname, label: 'New nickname', class: 'is-invalid' %>
          <%= f.password_field :password, label: 'New password', class: 'is-invalid' %>
        <% else %>
          <%= f.text_field :nickname, label: 'New nickname' %>
          <%= f.password_field :password, label: 'New password' %>
        <% end %>
        <%= f.primary 'Update user', control_class: "btn btn-outline-success" %>
      <% end %>
      <br/>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3" align="center">
      <table class="table table-bordered table-hover bg-white">
        <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>Nickname</th>
          <% if @_current_user.admin %>
            <th>For real admin</th>
          <% end %>
        </tr>
        </thead>

        <tbody>
        <% @users.each_with_index do |user, i| %>
          <tr>
            <td><%= i + 1 %></td>
            <td>
              <%= user.nickname %>
              <% if user.nickname == @_current_user.nickname %>
                <span class="text-muted">(It's you!)</span>
              <% end %>
            </td>
            <% if @_current_user.admin %>
              <td>
                  <%= link_to 'Destroy', user,
                              method: :delete,
                              data: { confirm: 'Are you sure?' },
                              class: 'btn btn-danger',
                              role: 'button' %>
              </td>
            <% end %>
            <!--td><%= link_to 'Show', user %></td-->
            <!--td><%= link_to 'Edit', edit_user_path(user) %></td-->
            <!--td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3" align="center">
      <h1>Create new user</h1>
      <%= bootstrap_form_for :user, url: '/users/create',local: true do |f| %>
        <% if flash[:danger] %>
          <%= f.text_field :nickname, label: 'Nickname', class: 'is-invalid' %>
          <%= f.password_field :password, label: 'Password', class: 'is-invalid' %>
        <% else %>
          <%= f.text_field :nickname, label: 'Nickname' %>
          <%= f.password_field :password, label: 'Password' %>
        <% end %>
        <%= f.primary 'Create user', control_class: "btn btn-outline-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3" align="center">
      <h2>
        <strong>Nickname:</strong>
        <%= @user.nickname %>
      </h2>
      <a class="btn btn-primary" href="<%= _back_url %>" role="button">Back</a>
      <a class="btn btn-primary" href="<%= edit_user_path(@user) %>" role="button">Edit</a>
    </div>
  </div>
</div>